spring.config.import=optional:classpath:secret.properties
server.port=8080

spring.application.name=horovod-hub-backend

# PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Horovod settings
horovod.max-concurrent-per-slot=2
horovod.max-log-entries=50
horovod.calendar-start-hour=8
horovod.calendar-end-hour=24
horovod.email-enabled=false

oauth.google.client = ${OAUTH_GOOGLE_CLIENT_SECRET:}
OAUTH_CLIENT_ID = ${OAUTH_GOOGLE_CLIENT_ID:}